apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: supabase-api
  description: Supabase API to get category hierarchy for users
spec:
  type: openapi
  lifecycle: production
  owner: team-name
  definition: |
    openapi: 3.0.0
    info:
      title: Supabase API
      version: 1.0.0
    paths:
      /rest/v1/rpc/get_category_hierarchy_for_users:
        post:
          summary: Get category hierarchy for users
          operationId: getCategoryHierarchyForUsers
          parameters:
            - in: header
              name: apikey
              required: true
              schema:
                type: string
              description: API key to authorize the request
            - in: header
              name: Authorization
              required: true
              schema:
                type: string
              description: Bearer token for authentication
          requestBody:
            required: true
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    org_id:
                      type: string
                      description: The organization ID for the request.
          responses:
            '200':
              description: Successfully fetched category hierarchy
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      hierarchy:
                        type: array
                        items:
                          type: object
                          properties:
                            category_id:
                              type: string
                            category_name:
                              type: string
            '400':
              description: Bad Request
            '401':
              description: Unauthorized
            '500':
              description: Internal Server Error
    servers:
      - url: https://kfpwszxuivydjftikxts.supabase.co
    components:
      securitySchemes:
        apikey:
          type: apiKey
          in: header
          name: apikey
        authorization:
          type: apiKey
          in: header
          name: Authorization
      security:
        - apikey: []
        - authorization: []
