apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: my-api
  description: My sample API for testing
spec:
  type: openapi
  lifecycle: production
  owner: team-name
  definition: |
    openapi: 3.0.0
    info:
      title: My API
      version: 1.0.0
    paths:
      /test:
        get:
          summary: Test API
          responses:
            '200':
              description: Success
